version: 0.2
env:
    variables:
        parameter-store:
            BUILD_OUTPUT_BUCKET: /Dev/buketname

phases:
    install:
        commands:
            - echo "Install phase"
            - pip install cfn-lint
            - cd codebuildgithub
            - npm install
    pre_build:
        commands:
            - echo "Pre-build phase"
            - npm test
            - eslint *.js
    build:
        commands:
        - echo "Build phase"
        - sam build
    post_build:
        commands:
        - echo "Post-build phase"
        - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --template-file template.yml --output-template-file packaged.yml

artifacts:
    files:
        - packaged.yml

